name: Test
on:
  push:
    paths:
      - '**/*.nix'
  workflow_dispatch:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          install_url: https://nixos-nix-install-tests.cachix.org/serve/vij683ly7sl95nnhb67bdjjfabclr85m/install
          install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: nix-instantiate --eval --strict test/test.nix
      - name: Test parameter parsing
        run: nix-instantiate --eval --strict test/testParams.nix
      - name: Check the derivation
        run: nix flake check --override-input org-babel ..
        working-directory: test
