name: Test
on:
  pull_request:
    paths:
      - '**/*.nix'
  push:
    branches:
      - master
    paths:
      - '**/*.nix'
  workflow_dispatch:
jobs:
  check:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V28
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: nix-instantiate --eval --strict test/test.nix
      - name: Test parameter parsing
        run: nix-instantiate --eval --strict test/testParams.nix
      - name: Check the derivation
        run: nix flake check --no-write-lock-file --override-input org-babel "path:$PWD/.."
        working-directory: test
